//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSend.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSend.Language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service.
        /// </summary>
        public static string AddService {
            get {
                return ResourceManager.GetString("AddService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        public static string Alarm0 {
            get {
                return ResourceManager.GetString("Alarm0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard limit triggered. Machine position is likely lost due to sudden and immediate halt..
        /// </summary>
        public static string Alarm1 {
            get {
                return ResourceManager.GetString("Alarm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-code motion target exceeds machine travel..
        /// </summary>
        public static string Alarm2 {
            get {
                return ResourceManager.GetString("Alarm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset while in motion. Grbl cannot guarantee position..
        /// </summary>
        public static string Alarm3 {
            get {
                return ResourceManager.GetString("Alarm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe fail. The probe is not in the expected initial state before starting probe cycle.
        /// </summary>
        public static string Alarm4 {
            get {
                return ResourceManager.GetString("Alarm4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe fail. Probe did not contact the workpiece.
        /// </summary>
        public static string Alarm5 {
            get {
                return ResourceManager.GetString("Alarm5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing fail. Reset during active homing cycle..
        /// </summary>
        public static string Alarm6 {
            get {
                return ResourceManager.GetString("Alarm6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing fail. Safety door was opened during active homing cycle..
        /// </summary>
        public static string Alarm7 {
            get {
                return ResourceManager.GetString("Alarm7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing fail. Cycle failed to clear limit switch when pulling off..
        /// </summary>
        public static string Alarm8 {
            get {
                return ResourceManager.GetString("Alarm8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing fail. Could not find limit switch within search distance..
        /// </summary>
        public static string Alarm9 {
            get {
                return ResourceManager.GetString("Alarm9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string AnalyserProperty {
            get {
                return ResourceManager.GetString("AnalyserProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string AnalyserValue {
            get {
                return ResourceManager.GetString("AnalyserValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser mode was disabled, changed to enabled as machine is a laser.
        /// </summary>
        public static string AutomaticallySelectedLaserMode {
            get {
                return ResourceManager.GetString("AutomaticallySelectedLaserMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser mode was enabled, changed to disabled as machine is CNC.
        /// </summary>
        public static string AutomaticallySelectedSpindleMode {
            get {
                return ResourceManager.GetString("AutomaticallySelectedSpindleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically set laser mode $32.
        /// </summary>
        public static string AutoUpdateLaserMode {
            get {
                return ResourceManager.GetString("AutoUpdateLaserMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically set spindle mode $32.
        /// </summary>
        public static string AutoUpdateSpindleMode {
            get {
                return ResourceManager.GetString("AutoUpdateSpindleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available bytes/blocks.
        /// </summary>
        public static string AvailableBytesBlocks {
            get {
                return ResourceManager.GetString("AvailableBytesBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Size: {0}.
        /// </summary>
        public static string BufferSize {
            get {
                return ResourceManager.GetString("BufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Alarm.
        /// </summary>
        public static string ClearAlarm {
            get {
                return ResourceManager.GetString("ClearAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear GCode.
        /// </summary>
        public static string ClearGCode {
            get {
                return ResourceManager.GetString("ClearGCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !! Grbl settings changed since last connected.
        /// </summary>
        public static string ConfigurationUpdatedSinceLastConnect {
            get {
                return ResourceManager.GetString("ConfigurationUpdatedSinceLastConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string Console {
            get {
                return ResourceManager.GetString("Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous.
        /// </summary>
        public static string Continuous {
            get {
                return ResourceManager.GetString("Continuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Coordinates.
        /// </summary>
        public static string CoordinateSystem {
            get {
                return ResourceManager.GetString("CoordinateSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Usage.
        /// </summary>
        public static string CPUUsage {
            get {
                return ResourceManager.GetString("CPUUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Feed Rate.
        /// </summary>
        public static string CurrentFeedRate {
            get {
                return ResourceManager.GetString("CurrentFeedRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Overrides.
        /// </summary>
        public static string DisableOverrides {
            get {
                return ResourceManager.GetString("DisableOverrides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inches.
        /// </summary>
        public static string DisplayInch {
            get {
                return ResourceManager.GetString("DisplayInch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string DisplayInchAbreviated {
            get {
                return ResourceManager.GetString("DisplayInchAbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inch/min.
        /// </summary>
        public static string DisplayInchMinute {
            get {
                return ResourceManager.GetString("DisplayInchMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inch/sec.
        /// </summary>
        public static string DisplayInchSecond {
            get {
                return ResourceManager.GetString("DisplayInchSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to millimeters.
        /// </summary>
        public static string DisplayMm {
            get {
                return ResourceManager.GetString("DisplayMm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string DisplayMmAbreviated {
            get {
                return ResourceManager.GetString("DisplayMmAbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm/min.
        /// </summary>
        public static string DisplayMmMinute {
            get {
                return ResourceManager.GetString("DisplayMmMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm/sec.
        /// </summary>
        public static string DisplayMmSec {
            get {
                return ResourceManager.GetString("DisplayMmSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display units.
        /// </summary>
        public static string DisplayUnits {
            get {
                return ResourceManager.GetString("DisplayUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically select from G Code file.
        /// </summary>
        public static string DisplayUpdateFromFile {
            get {
                return ResourceManager.GetString("DisplayUpdateFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined Grbl error.
        /// </summary>
        public static string Error0 {
            get {
                return ResourceManager.GetString("Error0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-code words consist of a letter and a value. Letter was not found.
        /// </summary>
        public static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft limits cannot be enabled without homing also enabled..
        /// </summary>
        public static string Error10 {
            get {
                return ResourceManager.GetString("Error10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max characters per line exceeded. File most likely formatted improperly.
        /// </summary>
        public static string Error11 {
            get {
                return ResourceManager.GetString("Error11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Grbl Error.
        /// </summary>
        public static string Error12 {
            get {
                return ResourceManager.GetString("Error12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Grbl Error.
        /// </summary>
        public static string Error13 {
            get {
                return ResourceManager.GetString("Error13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build info or startup line exceeded EEPROM line length limit. Line not stored..
        /// </summary>
        public static string Error14 {
            get {
                return ResourceManager.GetString("Error14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jog target exceeds machine travel. Jog command has been ignored..
        /// </summary>
        public static string Error15 {
            get {
                return ResourceManager.GetString("Error15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Grbl Error.
        /// </summary>
        public static string Error16 {
            get {
                return ResourceManager.GetString("Error16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser mode requires PWM output..
        /// </summary>
        public static string Error17 {
            get {
                return ResourceManager.GetString("Error17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Grbl Error.
        /// </summary>
        public static string Error18 {
            get {
                return ResourceManager.GetString("Error18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Grbl Error.
        /// </summary>
        public static string Error19 {
            get {
                return ResourceManager.GetString("Error19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing the expected G-code word value or numeric value format is not valid.
        /// </summary>
        public static string Error2 {
            get {
                return ResourceManager.GetString("Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported or invalid g-code command found in block. This usually means that you used the wrong post-Processor has been used..
        /// </summary>
        public static string Error20 {
            get {
                return ResourceManager.GetString("Error20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one g-code command from same modal group found in block.
        /// </summary>
        public static string Error21 {
            get {
                return ResourceManager.GetString("Error21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed rate has not yet been set or is undefined.
        /// </summary>
        public static string Error22 {
            get {
                return ResourceManager.GetString("Error22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-code command in block requires an integer value.
        /// </summary>
        public static string Error23 {
            get {
                return ResourceManager.GetString("Error23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one g-code command that requires axis words found in block.
        /// </summary>
        public static string Error24 {
            get {
                return ResourceManager.GetString("Error24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated g-code word found in block.
        /// </summary>
        public static string Error25 {
            get {
                return ResourceManager.GetString("Error25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No axis words found in block for g-code command or current modal state which requires them.
        /// </summary>
        public static string Error26 {
            get {
                return ResourceManager.GetString("Error26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line number value is invalid.
        /// </summary>
        public static string Error27 {
            get {
                return ResourceManager.GetString("Error27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-code command is missing a required value word.
        /// </summary>
        public static string Error28 {
            get {
                return ResourceManager.GetString("Error28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G59.x work coordinate systems are not supported.
        /// </summary>
        public static string Error29 {
            get {
                return ResourceManager.GetString("Error29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grbl ‘$’ system command was not recognized or supported.
        /// </summary>
        public static string Error3 {
            get {
                return ResourceManager.GetString("Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G53 only allowed with G0 and G1 motion modes.
        /// </summary>
        public static string Error30 {
            get {
                return ResourceManager.GetString("Error30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis words found in block when no command or current modal state uses them.
        /// </summary>
        public static string Error31 {
            get {
                return ResourceManager.GetString("Error31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G2 and G3 arcs require at least one in-plane axis word.
        /// </summary>
        public static string Error32 {
            get {
                return ResourceManager.GetString("Error32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion command target is invali.
        /// </summary>
        public static string Error33 {
            get {
                return ResourceManager.GetString("Error33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc radius value is invalid.
        /// </summary>
        public static string Error34 {
            get {
                return ResourceManager.GetString("Error34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G2 and G3 arcs require at least one in-plane offset word..
        /// </summary>
        public static string Error35 {
            get {
                return ResourceManager.GetString("Error35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused value words found in block..
        /// </summary>
        public static string Error36 {
            get {
                return ResourceManager.GetString("Error36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G43.1 dynamic tool length offset is not assigned to configured tool length axis..
        /// </summary>
        public static string Error37 {
            get {
                return ResourceManager.GetString("Error37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool number greater than max supported value.
        /// </summary>
        public static string Error38 {
            get {
                return ResourceManager.GetString("Error38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative value received for an expected positive value..
        /// </summary>
        public static string Error4 {
            get {
                return ResourceManager.GetString("Error4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing cycle failure. Homing is not enabled via settings..
        /// </summary>
        public static string Error5 {
            get {
                return ResourceManager.GetString("Error5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Grbl Error.
        /// </summary>
        public static string Error6 {
            get {
                return ResourceManager.GetString("Error6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An EEPROM read failed. Auto-restoring affected EEPROM to default values..
        /// </summary>
        public static string Error7 {
            get {
                return ResourceManager.GetString("Error7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grbl ‘$’ command cannot be used unless Grbl is IDLE. Ensures smooth operation during a job..
        /// </summary>
        public static string Error8 {
            get {
                return ResourceManager.GetString("Error8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-code commands are locked out during alarm or jog state..
        /// </summary>
        public static string Error9 {
            get {
                return ResourceManager.GetString("Error9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coolant is used but not turned off.
        /// </summary>
        public static string ErrorCoolantNotTurnedOff {
            get {
                return ResourceManager.GetString("ErrorCoolantNotTurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCode file uses a sub program {0} on line {1} which can not be found..
        /// </summary>
        public static string ErrorSubProgramMissing {
            get {
                return ResourceManager.GetString("ErrorSubProgramMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Rate Display.
        /// </summary>
        public static string FeedDisplay {
            get {
                return ResourceManager.GetString("FeedDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed.
        /// </summary>
        public static string FeedRate {
            get {
                return ResourceManager.GetString("FeedRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G Code Files|*.gcode;*.nc;*.ncc;*.ngc;*.tap;*.txt|All Files|*.*.
        /// </summary>
        public static string FileFilter {
            get {
                return ResourceManager.GetString("FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name:.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports flood coolant.
        /// </summary>
        public static string FloodCoolant {
            get {
                return ResourceManager.GetString("FloodCoolant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCode.
        /// </summary>
        public static string GCode {
            get {
                return ResourceManager.GetString("GCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Tool Changes.
        /// </summary>
        public static string GCodeAutomaticToolChanges {
            get {
                return ResourceManager.GetString("GCodeAutomaticToolChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Count.
        /// </summary>
        public static string GCodeCommandCount {
            get {
                return ResourceManager.GetString("GCodeCommandCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands After End.
        /// </summary>
        public static string GCodeCommandsAfterEnd {
            get {
                return ResourceManager.GetString("GCodeCommandsAfterEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string GCodeComments {
            get {
                return ResourceManager.GetString("GCodeComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains Duplicate Lines.
        /// </summary>
        public static string GCodeContainsDuplicates {
            get {
                return ResourceManager.GetString("GCodeContainsDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes Coordinate System.
        /// </summary>
        public static string GCodeCoordinates {
            get {
                return ResourceManager.GetString("GCodeCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate Systems.
        /// </summary>
        public static string GCodeCoordinateSystems {
            get {
                return ResourceManager.GetString("GCodeCoordinateSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File CRC.
        /// </summary>
        public static string GCodeFileCRC {
            get {
                return ResourceManager.GetString("GCodeFileCRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Created Time.
        /// </summary>
        public static string GCodeFileCreated {
            get {
                return ResourceManager.GetString("GCodeFileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Last Write Time.
        /// </summary>
        public static string GCodeFileLastWrite {
            get {
                return ResourceManager.GetString("GCodeFileLastWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size.
        /// </summary>
        public static string GCodeFileSize {
            get {
                return ResourceManager.GetString("GCodeFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood Coolant.
        /// </summary>
        public static string GCodeFloodCoolant {
            get {
                return ResourceManager.GetString("GCodeFloodCoolant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has End Program.
        /// </summary>
        public static string GCodeHasEndProgram {
            get {
                return ResourceManager.GetString("GCodeHasEndProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Z.
        /// </summary>
        public static string GCodeHomeZ {
            get {
                return ResourceManager.GetString("GCodeHomeZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Layers.
        /// </summary>
        public static string GCodeLayerCount {
            get {
                return ResourceManager.GetString("GCodeLayerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Count.
        /// </summary>
        public static string GCodeLineCount {
            get {
                return ResourceManager.GetString("GCodeLineCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Endings.
        /// </summary>
        public static string GCodeLineEndings {
            get {
                return ResourceManager.GetString("GCodeLineEndings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Layer Height.
        /// </summary>
        public static string GCodeMaxLayerHeight {
            get {
                return ResourceManager.GetString("GCodeMaxLayerHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max X/Y Feed Rate.
        /// </summary>
        public static string GCodeMaxXYFeed {
            get {
                return ResourceManager.GetString("GCodeMaxXYFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Z Feed Rate.
        /// </summary>
        public static string GCodeMaxZFeed {
            get {
                return ResourceManager.GetString("GCodeMaxZFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mist Coolant.
        /// </summary>
        public static string GCodeMistCoolant {
            get {
                return ResourceManager.GetString("GCodeMistCoolant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe Z.
        /// </summary>
        public static string GCodeSafeZ {
            get {
                return ResourceManager.GetString("GCodeSafeZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools Used.
        /// </summary>
        public static string GCodeToolsUsed {
            get {
                return ResourceManager.GetString("GCodeToolsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Distance.
        /// </summary>
        public static string GCodeTotalDistance {
            get {
                return ResourceManager.GetString("GCodeTotalDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time.
        /// </summary>
        public static string GCodeTotalTime {
            get {
                return ResourceManager.GetString("GCodeTotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns Off Coolant.
        /// </summary>
        public static string GCodeTurnOffCoolant {
            get {
                return ResourceManager.GetString("GCodeTurnOffCoolant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of Measure.
        /// </summary>
        public static string GCodeUnitOfMeasure {
            get {
                return ResourceManager.GetString("GCodeUnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not automatically detect unit of measure from GCode.
        /// </summary>
        public static string GCodeUnitOfMeasureError {
            get {
                return ResourceManager.GetString("GCodeUnitOfMeasureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grbl Settings.
        /// </summary>
        public static string GrblSettings {
            get {
                return ResourceManager.GetString("GrblSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${0}={1} ; {3} - Original value {1} was changed to {2}.
        /// </summary>
        public static string GrblValueUpdated {
            get {
                return ResourceManager.GetString("GrblValueUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string HelpAbout {
            get {
                return ResourceManager.GetString("HelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Help.
        /// </summary>
        public static string HelpView {
            get {
                return ResourceManager.GetString("HelpView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jog.
        /// </summary>
        public static string Jog {
            get {
                return ResourceManager.GetString("Jog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Icons.
        /// </summary>
        public static string LargeIcons {
            get {
                return ResourceManager.GetString("LargeIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please load a G Code file..
        /// </summary>
        public static string LoadFileForDetails {
            get {
                return ResourceManager.GetString("LoadFileForDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load GCode.
        /// </summary>
        public static string LoadGCode {
            get {
                return ResourceManager.GetString("LoadGCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        public static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Machine.
        /// </summary>
        public static string MachineAdd {
            get {
                return ResourceManager.GetString("MachineAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Switches.
        /// </summary>
        public static string MachineOptionLimitSwitches {
            get {
                return ResourceManager.GetString("MachineOptionLimitSwitches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool changer.
        /// </summary>
        public static string MachineOptionToolChanger {
            get {
                return ResourceManager.GetString("MachineOptionToolChanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Machines.
        /// </summary>
        public static string MachineRefresh {
            get {
                return ResourceManager.GetString("MachineRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Machine.
        /// </summary>
        public static string MachineRemove {
            get {
                return ResourceManager.GetString("MachineRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Settings.
        /// </summary>
        public static string MachineSettings {
            get {
                return ResourceManager.GetString("MachineSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Status.
        /// </summary>
        public static string MachineStatus {
            get {
                return ResourceManager.GetString("MachineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSend - {0} - {1}.
        /// </summary>
        public static string MachineTitle {
            get {
                return ResourceManager.GetString("MachineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain service schedule.
        /// </summary>
        public static string MaintainServiceSchedule {
            get {
                return ResourceManager.GetString("MaintainServiceSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports mist coolant.
        /// </summary>
        public static string MistCoolant {
            get {
                return ResourceManager.GetString("MistCoolant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Service.
        /// </summary>
        public static string NextService {
            get {
                return ResourceManager.GetString("NextService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} RPM.
        /// </summary>
        public static string OverrideRpm {
            get {
                return ResourceManager.GetString("OverrideRpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overrides.
        /// </summary>
        public static string Overrides {
            get {
                return ResourceManager.GetString("Overrides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string OverrideX {
            get {
                return ResourceManager.GetString("OverrideX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X/Y.
        /// </summary>
        public static string OverrideXY {
            get {
                return ResourceManager.GetString("OverrideXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string OverrideY {
            get {
                return ResourceManager.GetString("OverrideY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Down.
        /// </summary>
        public static string OverrideZDown {
            get {
                return ResourceManager.GetString("OverrideZDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Up.
        /// </summary>
        public static string OverrideZUp {
            get {
                return ResourceManager.GetString("OverrideZUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause All.
        /// </summary>
        public static string PauseAll {
            get {
                return ResourceManager.GetString("PauseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe.
        /// </summary>
        public static string Probe {
            get {
                return ResourceManager.GetString("Probe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe Command.
        /// </summary>
        public static string ProbeCommand {
            get {
                return ResourceManager.GetString("ProbeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe Thickness (mm).
        /// </summary>
        public static string ProbeThickness {
            get {
                return ResourceManager.GetString("ProbeThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe travel speed {0} {1}.
        /// </summary>
        public static string ProbeTravelSpeed {
            get {
                return ResourceManager.GetString("ProbeTravelSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probing failed, ensure you have a valid probing command setup..
        /// </summary>
        public static string ProbingFailed {
            get {
                return ResourceManager.GetString("ProbingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Size: {0}.
        /// </summary>
        public static string QueueSize {
            get {
                return ResourceManager.GetString("QueueSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string RapidRateHigh {
            get {
                return ResourceManager.GetString("RapidRateHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string RapidRateLow {
            get {
                return ResourceManager.GetString("RapidRateLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string RapidRateMedium {
            get {
                return ResourceManager.GetString("RapidRateMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapids.
        /// </summary>
        public static string Rapids {
            get {
                return ResourceManager.GetString("Rapids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Service.
        /// </summary>
        public static string RegisterService {
            get {
                return ResourceManager.GetString("RegisterService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume All.
        /// </summary>
        public static string ResumeAll {
            get {
                return ResourceManager.GetString("ResumeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Configuration.
        /// </summary>
        public static string SaveConfiguration {
            get {
                return ResourceManager.GetString("SaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to Server.
        /// </summary>
        public static string ServerConnected {
            get {
                return ResourceManager.GetString("ServerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Cpu {0}%.
        /// </summary>
        public static string ServerCpuStateConnected {
            get {
                return ResourceManager.GetString("ServerCpuStateConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Cpu -.
        /// </summary>
        public static string ServerCpuStateDisconnected {
            get {
                return ResourceManager.GetString("ServerCpuStateDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection to Server.
        /// </summary>
        public static string ServerNotConnected {
            get {
                return ResourceManager.GetString("ServerNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Date.
        /// </summary>
        public static string ServiceDate {
            get {
                return ResourceManager.GetString("ServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This machine&apos;s service is overdue!.
        /// </summary>
        public static string ServiceOverdue {
            get {
                return ResourceManager.GetString("ServiceOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This machine is due a service shortly!.
        /// </summary>
        public static string ServiceRequired {
            get {
                return ResourceManager.GetString("ServiceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Schedule.
        /// </summary>
        public static string ServiceSchedule {
            get {
                return ResourceManager.GetString("ServiceSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours of spindle usage.
        /// </summary>
        public static string ServiceSpindleHours {
            get {
                return ResourceManager.GetString("ServiceSpindleHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Type.
        /// </summary>
        public static string ServiceType {
            get {
                return ResourceManager.GetString("ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string ServiceTypeDaily {
            get {
                return ResourceManager.GetString("ServiceTypeDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        public static string ServiceTypeMajor {
            get {
                return ResourceManager.GetString("ServiceTypeMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor.
        /// </summary>
        public static string ServiceTypeMinor {
            get {
                return ResourceManager.GetString("ServiceTypeMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service every {0} weeks or.
        /// </summary>
        public static string ServiceWeeks {
            get {
                return ResourceManager.GetString("ServiceWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step pulse, microseconds.
        /// </summary>
        public static string SettingDescription0 {
            get {
                return ResourceManager.GetString("SettingDescription0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step idle delay, milliseconds.
        /// </summary>
        public static string SettingDescription1 {
            get {
                return ResourceManager.GetString("SettingDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status report, ‘?’ status.
        /// </summary>
        public static string SettingDescription10 {
            get {
                return ResourceManager.GetString("SettingDescription10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of X steps to move 1mm.
        /// </summary>
        public static string SettingDescription100 {
            get {
                return ResourceManager.GetString("SettingDescription100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Y steps to move 1mm.
        /// </summary>
        public static string SettingDescription101 {
            get {
                return ResourceManager.GetString("SettingDescription101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Z steps to move 1mm.
        /// </summary>
        public static string SettingDescription102 {
            get {
                return ResourceManager.GetString("SettingDescription102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junction deviation, mm.
        /// </summary>
        public static string SettingDescription11 {
            get {
                return ResourceManager.GetString("SettingDescription11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Max rate, mm/min.
        /// </summary>
        public static string SettingDescription110 {
            get {
                return ResourceManager.GetString("SettingDescription110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Max rate, mm/min.
        /// </summary>
        public static string SettingDescription111 {
            get {
                return ResourceManager.GetString("SettingDescription111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Max rate, mm/min.
        /// </summary>
        public static string SettingDescription112 {
            get {
                return ResourceManager.GetString("SettingDescription112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc tolerance, mm.
        /// </summary>
        public static string SettingDescription12 {
            get {
                return ResourceManager.GetString("SettingDescription12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Acceleration, mm/sec^2.
        /// </summary>
        public static string SettingDescription120 {
            get {
                return ResourceManager.GetString("SettingDescription120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Acceleration, mm/sec^2.
        /// </summary>
        public static string SettingDescription121 {
            get {
                return ResourceManager.GetString("SettingDescription121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Acceleration, mm/sec^2.
        /// </summary>
        public static string SettingDescription122 {
            get {
                return ResourceManager.GetString("SettingDescription122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report mode.
        /// </summary>
        public static string SettingDescription13 {
            get {
                return ResourceManager.GetString("SettingDescription13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Max travel, mm Only for Homing and Soft Limits.
        /// </summary>
        public static string SettingDescription130 {
            get {
                return ResourceManager.GetString("SettingDescription130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Max travel, mm Only for Homing and Soft Limits.
        /// </summary>
        public static string SettingDescription131 {
            get {
                return ResourceManager.GetString("SettingDescription131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Max travel, mm Only for Homing and Soft Limits.
        /// </summary>
        public static string SettingDescription132 {
            get {
                return ResourceManager.GetString("SettingDescription132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step port invert, XYZmask.
        /// </summary>
        public static string SettingDescription2 {
            get {
                return ResourceManager.GetString("SettingDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft limits, (Homing must be enabled).
        /// </summary>
        public static string SettingDescription20 {
            get {
                return ResourceManager.GetString("SettingDescription20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard limits.
        /// </summary>
        public static string SettingDescription21 {
            get {
                return ResourceManager.GetString("SettingDescription21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing cycle.
        /// </summary>
        public static string SettingDescription22 {
            get {
                return ResourceManager.GetString("SettingDescription22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing direction invert, XYZmask.
        /// </summary>
        public static string SettingDescription23 {
            get {
                return ResourceManager.GetString("SettingDescription23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing feed, mm/min.
        /// </summary>
        public static string SettingDescription24 {
            get {
                return ResourceManager.GetString("SettingDescription24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing seek, mm/min.
        /// </summary>
        public static string SettingDescription25 {
            get {
                return ResourceManager.GetString("SettingDescription25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing debounce, milliseconds.
        /// </summary>
        public static string SettingDescription26 {
            get {
                return ResourceManager.GetString("SettingDescription26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing pull-off, mm.
        /// </summary>
        public static string SettingDescription27 {
            get {
                return ResourceManager.GetString("SettingDescription27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction port invert, XYZmask.
        /// </summary>
        public static string SettingDescription3 {
            get {
                return ResourceManager.GetString("SettingDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max spindle speed, RPM.
        /// </summary>
        public static string SettingDescription30 {
            get {
                return ResourceManager.GetString("SettingDescription30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min spindle speed, RPM.
        /// </summary>
        public static string SettingDescription31 {
            get {
                return ResourceManager.GetString("SettingDescription31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser mode.
        /// </summary>
        public static string SettingDescription32 {
            get {
                return ResourceManager.GetString("SettingDescription32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step enable invert.
        /// </summary>
        public static string SettingDescription4 {
            get {
                return ResourceManager.GetString("SettingDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit pins invert.
        /// </summary>
        public static string SettingDescription5 {
            get {
                return ResourceManager.GetString("SettingDescription5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe pin invert.
        /// </summary>
        public static string SettingDescription6 {
            get {
                return ResourceManager.GetString("SettingDescription6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting have changed or been updated.
        /// </summary>
        public static string SettingsChanged {
            get {
                return ResourceManager.GetString("SettingsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% of Maximum Feed Rate.
        /// </summary>
        public static string SpeedPercent {
            get {
                return ResourceManager.GetString("SpeedPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} RPM.
        /// </summary>
        public static string SpeedRpm {
            get {
                return ResourceManager.GetString("SpeedRpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spindle.
        /// </summary>
        public static string Spindle {
            get {
                return ResourceManager.GetString("Spindle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string SpindleActive {
            get {
                return ResourceManager.GetString("SpindleActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CW {0} RPM.
        /// </summary>
        public static string SpindleClockwise {
            get {
                return ResourceManager.GetString("SpindleClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spindle Control.
        /// </summary>
        public static string SpindleControl {
            get {
                return ResourceManager.GetString("SpindleControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCW {0} RPM.
        /// </summary>
        public static string SpindleCounterClockwise {
            get {
                return ResourceManager.GetString("SpindleCounterClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay start for {0} seconds.
        /// </summary>
        public static string SpindleDelayStartVFD {
            get {
                return ResourceManager.GetString("SpindleDelayStartVFD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Clockwise.
        /// </summary>
        public static string SpindleDirectionCounterClockwise {
            get {
                return ResourceManager.GetString("SpindleDirectionCounterClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        public static string SpindleExternal {
            get {
                return ResourceManager.GetString("SpindleExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spindle Status.
        /// </summary>
        public static string SpindleHint {
            get {
                return ResourceManager.GetString("SpindleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spindle Hours.
        /// </summary>
        public static string SpindleHours {
            get {
                return ResourceManager.GetString("SpindleHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string SpindleInactive {
            get {
                return ResourceManager.GetString("SpindleInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated.
        /// </summary>
        public static string SpindleIntegrated {
            get {
                return ResourceManager.GetString("SpindleIntegrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft start/stop.
        /// </summary>
        public static string SpindleSoftStart {
            get {
                return ResourceManager.GetString("SpindleSoftStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup over {0} seconds.
        /// </summary>
        public static string SpindleSoftStartSeconds {
            get {
                return ResourceManager.GetString("SpindleSoftStartSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string SpindleStart {
            get {
                return ResourceManager.GetString("SpindleStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string SpindleStop {
            get {
                return ResourceManager.GetString("SpindleStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spindle Type.
        /// </summary>
        public static string SpindleType {
            get {
                return ResourceManager.GetString("SpindleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VFD.
        /// </summary>
        public static string SpindleVFD {
            get {
                return ResourceManager.GetString("SpindleVFD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Job Wizard.
        /// </summary>
        public static string StartJobWizard {
            get {
                return ResourceManager.GetString("StartJobWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start or Resume.
        /// </summary>
        public static string StartOrResume {
            get {
                return ResourceManager.GetString("StartOrResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        public static string StateAlarm {
            get {
                return ResourceManager.GetString("StateAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string StateCheck {
            get {
                return ResourceManager.GetString("StateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door.
        /// </summary>
        public static string StateDoor {
            get {
                return ResourceManager.GetString("StateDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        public static string StateHold {
            get {
                return ResourceManager.GetString("StateHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string StateHome {
            get {
                return ResourceManager.GetString("StateHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string StateIdle {
            get {
                return ResourceManager.GetString("StateIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jog.
        /// </summary>
        public static string StateJog {
            get {
                return ResourceManager.GetString("StateJog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string StatePaused {
            get {
                return ResourceManager.GetString("StatePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Open.
        /// </summary>
        public static string StatePortOpen {
            get {
                return ResourceManager.GetString("StatePortOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probing.
        /// </summary>
        public static string StateProbing {
            get {
                return ResourceManager.GetString("StateProbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string StateRun {
            get {
                return ResourceManager.GetString("StateRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        public static string StateSleep {
            get {
                return ResourceManager.GetString("StateSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string StateUnknown {
            get {
                return ResourceManager.GetString("StateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spindle time remaining: {0} hours and {1} minutes.
        /// </summary>
        public static string StatusServiceSpindleTime {
            get {
                return ResourceManager.GetString("StatusServiceSpindleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps.
        /// </summary>
        public static string Steps {
            get {
                return ResourceManager.GetString("Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Programs.
        /// </summary>
        public static string SubPrograms {
            get {
                return ResourceManager.GetString("SubPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCode file uses {0}, display set to {1}.  Updating display to {0}.
        /// </summary>
        public static string UpdatingUnitOfMeasureFromGCode {
            get {
                return ResourceManager.GetString("UpdatingUnitOfMeasureFromGCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCode file contains option to turn on flood coolant but is not supported.  This command will be ignored..
        /// </summary>
        public static string WarningContainsFloodCoolantOption {
            get {
                return ResourceManager.GetString("WarningContainsFloodCoolantOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCode file contains option to turn on mist coolant but is not supported.  This command will be ignored..
        /// </summary>
        public static string WarningContainsMistCoolantOption {
            get {
                return ResourceManager.GetString("WarningContainsMistCoolantOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCode file contains option to change tools but is not supported.  This command will be ignored..
        /// </summary>
        public static string WarningContainsToolChangeOption {
            get {
                return ResourceManager.GetString("WarningContainsToolChangeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum layer height is {0} which exceeds warning level of {1}.
        /// </summary>
        public static string WarningLayerHeightTooMuch {
            get {
                return ResourceManager.GetString("WarningLayerHeightTooMuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors, warnings and information count.
        /// </summary>
        public static string WarningsAndInformation {
            get {
                return ResourceManager.GetString("WarningsAndInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn if layer height is more than.
        /// </summary>
        public static string WarnLayerHeight {
            get {
                return ResourceManager.GetString("WarnLayerHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
