//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSend.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSend.Language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        public static string Alarm0 {
            get {
                return ResourceManager.GetString("Alarm0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard limit triggered. Machine position is likely lost due to sudden and immediate halt..
        /// </summary>
        public static string Alarm1 {
            get {
                return ResourceManager.GetString("Alarm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-code motion target exceeds machine travel..
        /// </summary>
        public static string Alarm2 {
            get {
                return ResourceManager.GetString("Alarm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset while in motion. Grbl cannot guarantee position..
        /// </summary>
        public static string Alarm3 {
            get {
                return ResourceManager.GetString("Alarm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe fail. The probe is not in the expected initial state before starting probe cycle.
        /// </summary>
        public static string Alarm4 {
            get {
                return ResourceManager.GetString("Alarm4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe fail. Probe did not contact the workpiece.
        /// </summary>
        public static string Alarm5 {
            get {
                return ResourceManager.GetString("Alarm5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing fail. Reset during active homing cycle..
        /// </summary>
        public static string Alarm6 {
            get {
                return ResourceManager.GetString("Alarm6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing fail. Safety door was opened during active homing cycle..
        /// </summary>
        public static string Alarm7 {
            get {
                return ResourceManager.GetString("Alarm7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing fail. Cycle failed to clear limit switch when pulling off..
        /// </summary>
        public static string Alarm8 {
            get {
                return ResourceManager.GetString("Alarm8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing fail. Could not find limit switch within search distance..
        /// </summary>
        public static string Alarm9 {
            get {
                return ResourceManager.GetString("Alarm9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Alarm.
        /// </summary>
        public static string ClearAlarm {
            get {
                return ResourceManager.GetString("ClearAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !! Grbl settings changed since last connected.
        /// </summary>
        public static string ConfigurationUpdatedSinceLastConnect {
            get {
                return ResourceManager.GetString("ConfigurationUpdatedSinceLastConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous.
        /// </summary>
        public static string Continuous {
            get {
                return ResourceManager.GetString("Continuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Usage.
        /// </summary>
        public static string CPUUsage {
            get {
                return ResourceManager.GetString("CPUUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Overrides.
        /// </summary>
        public static string DisableOverrides {
            get {
                return ResourceManager.GetString("DisableOverrides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inch/min.
        /// </summary>
        public static string DisplayInchMinute {
            get {
                return ResourceManager.GetString("DisplayInchMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inch/sec.
        /// </summary>
        public static string DisplayInchSecond {
            get {
                return ResourceManager.GetString("DisplayInchSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm/min.
        /// </summary>
        public static string DisplayMmMinute {
            get {
                return ResourceManager.GetString("DisplayMmMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm/sec.
        /// </summary>
        public static string DisplayMmSec {
            get {
                return ResourceManager.GetString("DisplayMmSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed.
        /// </summary>
        public static string FeedRate {
            get {
                return ResourceManager.GetString("FeedRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grbl Settings.
        /// </summary>
        public static string GrblSettings {
            get {
                return ResourceManager.GetString("GrblSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${0}={1} ; {3} - Original value {1} was changed to {2}.
        /// </summary>
        public static string GrblValueUpdated {
            get {
                return ResourceManager.GetString("GrblValueUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        public static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Machine.
        /// </summary>
        public static string MachineAdd {
            get {
                return ResourceManager.GetString("MachineAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Machines.
        /// </summary>
        public static string MachineRefresh {
            get {
                return ResourceManager.GetString("MachineRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSend - {0} - {1}.
        /// </summary>
        public static string MachineTitle {
            get {
                return ResourceManager.GetString("MachineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} RPM.
        /// </summary>
        public static string OverrideRpm {
            get {
                return ResourceManager.GetString("OverrideRpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overrides.
        /// </summary>
        public static string Overrides {
            get {
                return ResourceManager.GetString("Overrides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause All.
        /// </summary>
        public static string PauseAll {
            get {
                return ResourceManager.GetString("PauseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe.
        /// </summary>
        public static string Probe {
            get {
                return ResourceManager.GetString("Probe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe Command.
        /// </summary>
        public static string ProbeCommand {
            get {
                return ResourceManager.GetString("ProbeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe Thickness (mm).
        /// </summary>
        public static string ProbeThickness {
            get {
                return ResourceManager.GetString("ProbeThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe travel speed {0}mm/min.
        /// </summary>
        public static string ProbeTravelSpeed {
            get {
                return ResourceManager.GetString("ProbeTravelSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probing failed, ensure you have a valid probing command setup..
        /// </summary>
        public static string ProbingFailed {
            get {
                return ResourceManager.GetString("ProbingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume All.
        /// </summary>
        public static string ResumeAll {
            get {
                return ResourceManager.GetString("ResumeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to Server.
        /// </summary>
        public static string ServerConnected {
            get {
                return ResourceManager.GetString("ServerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Cpu {0}%.
        /// </summary>
        public static string ServerCpuStateConnected {
            get {
                return ResourceManager.GetString("ServerCpuStateConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Cpu -.
        /// </summary>
        public static string ServerCpuStateDisconnected {
            get {
                return ResourceManager.GetString("ServerCpuStateDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection to Server.
        /// </summary>
        public static string ServerNotConnected {
            get {
                return ResourceManager.GetString("ServerNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Schedule.
        /// </summary>
        public static string ServiceSchedule {
            get {
                return ResourceManager.GetString("ServiceSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step pulse, microseconds.
        /// </summary>
        public static string SettingDescription0 {
            get {
                return ResourceManager.GetString("SettingDescription0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step idle delay, milliseconds.
        /// </summary>
        public static string SettingDescription1 {
            get {
                return ResourceManager.GetString("SettingDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status report, ‘?’ status.
        /// </summary>
        public static string SettingDescription10 {
            get {
                return ResourceManager.GetString("SettingDescription10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of X steps to move 1mm.
        /// </summary>
        public static string SettingDescription100 {
            get {
                return ResourceManager.GetString("SettingDescription100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Y steps to move 1mm.
        /// </summary>
        public static string SettingDescription101 {
            get {
                return ResourceManager.GetString("SettingDescription101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Z steps to move 1mm.
        /// </summary>
        public static string SettingDescription102 {
            get {
                return ResourceManager.GetString("SettingDescription102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junction deviation, mm.
        /// </summary>
        public static string SettingDescription11 {
            get {
                return ResourceManager.GetString("SettingDescription11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Max rate, mm/min.
        /// </summary>
        public static string SettingDescription110 {
            get {
                return ResourceManager.GetString("SettingDescription110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Max rate, mm/min.
        /// </summary>
        public static string SettingDescription111 {
            get {
                return ResourceManager.GetString("SettingDescription111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Max rate, mm/min.
        /// </summary>
        public static string SettingDescription112 {
            get {
                return ResourceManager.GetString("SettingDescription112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc tolerance, mm.
        /// </summary>
        public static string SettingDescription12 {
            get {
                return ResourceManager.GetString("SettingDescription12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Acceleration, mm/sec^2.
        /// </summary>
        public static string SettingDescription120 {
            get {
                return ResourceManager.GetString("SettingDescription120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Acceleration, mm/sec^2.
        /// </summary>
        public static string SettingDescription121 {
            get {
                return ResourceManager.GetString("SettingDescription121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Acceleration, mm/sec^2.
        /// </summary>
        public static string SettingDescription122 {
            get {
                return ResourceManager.GetString("SettingDescription122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report mode.
        /// </summary>
        public static string SettingDescription13 {
            get {
                return ResourceManager.GetString("SettingDescription13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Max travel, mm Only for Homing and Soft Limits.
        /// </summary>
        public static string SettingDescription130 {
            get {
                return ResourceManager.GetString("SettingDescription130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Max travel, mm Only for Homing and Soft Limits.
        /// </summary>
        public static string SettingDescription131 {
            get {
                return ResourceManager.GetString("SettingDescription131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Max travel, mm Only for Homing and Soft Limits.
        /// </summary>
        public static string SettingDescription132 {
            get {
                return ResourceManager.GetString("SettingDescription132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step port invert, XYZmask.
        /// </summary>
        public static string SettingDescription2 {
            get {
                return ResourceManager.GetString("SettingDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft limits, (Homing must be enabled).
        /// </summary>
        public static string SettingDescription20 {
            get {
                return ResourceManager.GetString("SettingDescription20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard limits.
        /// </summary>
        public static string SettingDescription21 {
            get {
                return ResourceManager.GetString("SettingDescription21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing cycle.
        /// </summary>
        public static string SettingDescription22 {
            get {
                return ResourceManager.GetString("SettingDescription22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing direction invert, XYZmask.
        /// </summary>
        public static string SettingDescription23 {
            get {
                return ResourceManager.GetString("SettingDescription23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing feed, mm/min.
        /// </summary>
        public static string SettingDescription24 {
            get {
                return ResourceManager.GetString("SettingDescription24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing seek, mm/min.
        /// </summary>
        public static string SettingDescription25 {
            get {
                return ResourceManager.GetString("SettingDescription25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing debounce, milliseconds.
        /// </summary>
        public static string SettingDescription26 {
            get {
                return ResourceManager.GetString("SettingDescription26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing pull-off, mm.
        /// </summary>
        public static string SettingDescription27 {
            get {
                return ResourceManager.GetString("SettingDescription27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction port invert, XYZmask.
        /// </summary>
        public static string SettingDescription3 {
            get {
                return ResourceManager.GetString("SettingDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max spindle speed, RPM.
        /// </summary>
        public static string SettingDescription30 {
            get {
                return ResourceManager.GetString("SettingDescription30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min spindle speed, RPM.
        /// </summary>
        public static string SettingDescription31 {
            get {
                return ResourceManager.GetString("SettingDescription31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser mode.
        /// </summary>
        public static string SettingDescription32 {
            get {
                return ResourceManager.GetString("SettingDescription32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step enable invert.
        /// </summary>
        public static string SettingDescription4 {
            get {
                return ResourceManager.GetString("SettingDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit pins invert.
        /// </summary>
        public static string SettingDescription5 {
            get {
                return ResourceManager.GetString("SettingDescription5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe pin invert.
        /// </summary>
        public static string SettingDescription6 {
            get {
                return ResourceManager.GetString("SettingDescription6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting have changed or been updated.
        /// </summary>
        public static string SettingsChanged {
            get {
                return ResourceManager.GetString("SettingsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% of Speed.
        /// </summary>
        public static string SpeedPercent {
            get {
                return ResourceManager.GetString("SpeedPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} RPM.
        /// </summary>
        public static string SpeedRpm {
            get {
                return ResourceManager.GetString("SpeedRpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spindle.
        /// </summary>
        public static string Spindle {
            get {
                return ResourceManager.GetString("Spindle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay start for {0} seconds.
        /// </summary>
        public static string SpindleDelayStartVFD {
            get {
                return ResourceManager.GetString("SpindleDelayStartVFD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        public static string SpindleExternal {
            get {
                return ResourceManager.GetString("SpindleExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated.
        /// </summary>
        public static string SpindleIntegrated {
            get {
                return ResourceManager.GetString("SpindleIntegrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft start.
        /// </summary>
        public static string SpindleSoftStart {
            get {
                return ResourceManager.GetString("SpindleSoftStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup over {0} seconds.
        /// </summary>
        public static string SpindleSoftStartSeconds {
            get {
                return ResourceManager.GetString("SpindleSoftStartSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spindle Type.
        /// </summary>
        public static string SpindleType {
            get {
                return ResourceManager.GetString("SpindleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VFD.
        /// </summary>
        public static string SpindleVFD {
            get {
                return ResourceManager.GetString("SpindleVFD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        public static string StateAlarm {
            get {
                return ResourceManager.GetString("StateAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string StateCheck {
            get {
                return ResourceManager.GetString("StateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door.
        /// </summary>
        public static string StateDoor {
            get {
                return ResourceManager.GetString("StateDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        public static string StateHold {
            get {
                return ResourceManager.GetString("StateHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string StateHome {
            get {
                return ResourceManager.GetString("StateHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string StateIdle {
            get {
                return ResourceManager.GetString("StateIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jog.
        /// </summary>
        public static string StateJog {
            get {
                return ResourceManager.GetString("StateJog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string StatePaused {
            get {
                return ResourceManager.GetString("StatePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Open.
        /// </summary>
        public static string StatePortOpen {
            get {
                return ResourceManager.GetString("StatePortOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probing.
        /// </summary>
        public static string StateProbing {
            get {
                return ResourceManager.GetString("StateProbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string StateRun {
            get {
                return ResourceManager.GetString("StateRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        public static string StateSleep {
            get {
                return ResourceManager.GetString("StateSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string StateUnknown {
            get {
                return ResourceManager.GetString("StateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps.
        /// </summary>
        public static string Steps {
            get {
                return ResourceManager.GetString("Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
